### ISSUE TITLE
Epic: English-Words Project Roadmap 🗺️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/english-words#154]
# Just Want a List of Words? ❓ 

If you only care about the list of words in this repo, 📝 
that's great; use them and have an awesome day! 🎉 

![donaldtrum-best-words](https://user-images.githubusercontent.com/194400/200817775-08930290-c2b0-4a86-a41e-3326f6ef5a56.gif)

# Want _More_? 🚀 

For the minuscule minority of people who want _more_, this issue is for you! 🙌 

![oliver-please-have-some-more](https://user-images.githubusercontent.com/194400/200817858-c876727d-cf64-427f-8056-4ba3cea22743.gif)

# _Brief_ History / Context

A few years ago I needed a list of **English Words** for a **work** project. 👨‍💻 
Went searching and didn't find a ready-made list of English Words ... 🔍 🤷‍♂️  

But found this StackOverflow Question and Answer:
[https://stackoverflow.com/questions/2213607/how-to-get-english-language-word-database](https://stackoverflow.com/a/2213622/1148249)     

<img width="965" alt="stackoverflow-english-words" src="https://user-images.githubusercontent.com/194400/200818848-0baa4a3e-f04a-454c-b1d3-cd836ca43046.png">

Extracted the words from the Excel file that was on InfoChimps (now **`404`**) and dumped them in a **`.txt`** file.
Put it on **`GitHub`** and linked to it in a comment on SO and didn't give it anymore thought. 👌 

Sadly, the **work** project that used the words was **_closed_ source** for a company that got acquired and the App was shut down. 😢  The folly of working on **_closed_ source** things is that you often have **_nothing_ to show** for your **_years_ of your life**! 💭     

### Meanwhile **_many_ thousands** of people have downloaded the word list and the repo has **`8.3k`** ⭐ 🤯 

The mini [Open Source] demo project I created: [nelsonic/**autocomplete**](https://github.com/nelsonic/autocomplete) ➡️ [**wordsy**.herokuapp.com](https://wordsy.herokuapp.com) ...

![autocomplete-wordsy-demo](https://user-images.githubusercontent.com/194400/200622601-700d8cf9-c116-4a23-b25f-de37ababf3d4.gif)

will soon be taken offline by [Heroku's Bean-counters](https://github.com/dwyl/learn-heroku/issues/52) 🙄 

I _outlined_ what I wanted to do in [autocomplete#**tasks**](https://github.com/nelsonic/autocomplete#tasks) but it's very incomplete ...
so this issue will give a _muuuuch_ better roadmap of what we're doing. 🤞 

# What challenge are we _solving_? 🤔 

The original purpose of this repo will 100% be maintained. ✅ 
What we are doing is _enhancing_ the repo with a showcase **App** that allows people to:

With that in mind, this is the plan:

1. **High quality list of English words** in an easy to extract file/format e.g. **`.txt`**, **`.json`** and **`.zip`** 
2. **Instructions** for how to _use_ the words in various programming languages; **`code` examples**.
  + [ ] `JavaScript`/`TypeScript`
  + [ ] `Python`
  + [ ] `Elixir`
  + [ ] `Dart`
  + [ ] `Rust`
  + [ ] Invite _contributions_ from the community for `code` examples from more programming languages [but NOT frameworks]
  Make it clear that we _really don't_ want a [**`React`**](https://github.com/dwyl/learn-react/issues/23) sample because we don't want to encourage _anyone_ to use it. 
3. Clarity on the **Process** for **_updating_ the words list** both adding, correcting and _removing_ [invalid] words.
4. Automate the creation of the `.zip` file so that we don't have people attempting to submit Pull Requests with Zip Files.

> We're _never_ going to accept a PR with a zip file. It's an _easy_ attack vector for a malicious auto-executable. 
> Read more: https://github.com/snyk/zip-slip-vulnerability
> It's not that we don't "trust" people ... but we know that not _everyone_ on GitHub has good intentions. 
> Crime pays otherwise there wouldn't be any crims ... And cyber-crime pays big BTCs! So let's just avoid it. 👌 

5. Allow _anyone_ to lookup words with auto-completion and to make suggestions via Web App/UI. That will invite _way_ more people including non-technical people who don't know how to use GitHub to help maintain+improve the list of words.

 
# Todo

+ [ ] **_Create_ `Phoenix` App** 🆕 ... **Note**: waiting for [`Phoenix v1.7`](https://github.com/dwyl/learn-phoenix-framework/issues/152) to do this to minimise time wasted with updates ... ⏳ 
+ [ ] **_Re_-create** basic features from [nelsonic/**autocomplete**](https://github.com/nelsonic/autocomplete):
  + [ ] Use **`PostgreSQL`** for simplicity. 
  + [ ] If we notice too much query latency, we can switch to [**`SQLite`**](https://github.com/dwyl/technology-stack/issues/92) or [**`ETS`**](https://elixirschool.com/en/lessons/storage/ets) for speed: 
+ [ ] Load the _current_ English Words List into the DB 
+ [ ] Determine/decide what other metadata we want to store for each word. 💭 
+ [ ] Discuss any other features we want to have. (please comment!) 💬

**Comment by nelsonic** [comment]
@LuchoTurtle does this answer your questions regarding the "roadmap" for this repo? 💭 🤞

**Comment by clach04** [comment]
Created https://github.com/dwyl/english-words/issues/211 for number 4 in the proposed roadmap.
