### ISSUE TITLE
Chore: Review all the open Pull Requests and Attempt to merge them 🧑‍💻 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/english-words#155]
At present there are **`20`** open Pull Requests: https://github.com/dwyl/english-words/pulls

![image](https://user-images.githubusercontent.com/194400/201072761-3da45b36-dc57-44d8-b17d-6c8578c42c2b.png)

This is both a _great_ and a _really bad_ sign. 🎉 😕 

On the positive side it's _awesome_ that people _want_ to **contribute**  to the project 
[not just take the words and give nothing back...] 
and continually renews my faith in Open Source! 😍 

But the down-side of having so many PRs open is that the efforts of _several_ people are wasted ... 😞
ewe need to do a _much_ better job of communicating how to contribute. 

https://github.com/dwyl/english-words/pull/130 is an example of one that clearly took some effort and will add value to people! 👌 
So we need to make every effort to ensure that the effort was not wasted! ⏳ 

> **Note**: this is **`priority-3`** ("_nice to have_") because `while` we definitely want to maintain and _improve_ this repo, we have extremely limited time. And since we are not _currently_ using it in our [**`App`**](https://github.com/dwyl/app) ... we cannot justify the time allocation/investment right now. That's why I've "ignored" the open PRs. 🙄 
Only features that relate to the [**`App`**](https://github.com/dwyl/app) are given higher priority. 
It's _possible_ that we could use English Words in the App e.g. for auto-completion/suggestion.
In which case the priority of updating/maintaining this repo/project would be raised.

# Todo

+ [ ] Review the PR: 👀 
  + [ ] Assign it to yourself and add the label: **`in-review`** 👨‍🏫 
  + [ ] View the code/words updates and leave comments 💬 
  + [ ] If you feel it's immediately mergeable, approve it and assign it to me. 🙏 
  + [ ] If it's not mergable, please leave a comment for the author (including an apology for the delay and link to this issue) 🔗 

+ [ ] Criteria that qualifies for merging: 
  + [ ] Minor code change where CI passes. ✅  e.g: https://github.com/dwyl/english-words/pull/153
  + [ ] Word change that references an issue where it was previously discussed. ✅ 
+ [ ] Instantly reject PRs that update **`Zip` files** and explain that **`Zip` files** files are commonly used for viruses so we cannot afford to trust _anyone_ with updating them.  "It's not you, it's me/us" we "Trust No One" https://en.wikipedia.org/wiki/Trust_no_one_(Internet_security)

@LuchoTurtle you mentioned this repo to me verbally in our catch up yesterday.
If you want to make a stab at reviewing the open PRs in a Pomodoro Break, go for it!
Please just leave a comment on this issue first and link to the PR you're picking off.

**Comment by LuchoTurtle** [comment]
In my downtime, I may try to clean up this repo. I've a handful of questions, though:

- there are a few PRs that are useful and quickly mergeable (like #190) but that do not have a pertaining issue. Should I merge these as well?
- I'd appreciate more clarification with the `zip` files. Are these generated from any script inside the `script` folder? If we are not meant to update `zip` files, how will we maintain consistency with the 	`.txt` file? (we have stuff like https://github.com/dwyl/english-words/issues/164 happening).
- would it be useful to add a Github Action pipeline to generate these `zip` files whenever a branch is merged into the `main` branch? Again, more clarification on these `zip` files would be appreciated :)

**Comment by nelsonic** [comment]
@LuchoTurtle GitHub isn't great for managing large files like this. 
I would _much_ rather be a bit more _ambitious_ with this project and build a (Web) `UI` for easily accessing the words.
With a simple "download `zip` file" button that compiles the zip in real time and gives people the _latest_ version of the list as line separated list. 

Yes, this will invalidate the _current_ pull requests (which can all be merged to not waste contributors) 
but will be a more sustainable long-term solution that we can do _more_ with.
